name: 'Check all reviewers are approved'
description: 'checking if all reviewers are approved the PR'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node14'
  main: 'index.js'
